export const shootCategories = {
  portfolio: {
    title: "Portfolio Shoot",
    icon: "🖼",
    tagline: "Define Your Professional Identity",
    banner: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1400&q=80",
    packages: [
      {
        id: "portfolio-basic",
        name: "Starter Portfolio",
        price: 4999,
        duration: "2 Hours",
        photos: "20 Edited Photos",
        description: "Perfect for freshers & students building their first professional portfolio.",
        images: [
          "/Portfolio/2.jpg",
          "/Portfolio/3.jpg",
          "/Portfolio/4.jpg",
          "/Portfolio/5.jpg",
        ],
        includes: ["Professional lighting setup", "2 outfit changes", "Digital delivery", "Basic retouching"],
      },
      {
        id: "portfolio-pro",
        name: "Professional Portfolio",
        price: 9999,
        duration: "4 Hours",
        photos: "50 Edited Photos",
        description: "For models, actors & professionals who need a standout portfolio.",
        images: [
          "/Portfolio/6.jpg",
          "/Portfolio/7.jpg",
          "/Portfolio/8.jpg",
          "/Portfolio/9.jpg",
        ],
        includes: ["Studio + outdoor shots", "5 outfit changes", "Makeup artist included", "Advanced retouching", "Printed album"],
      },
      {
        id: "portfolio-elite",
        name: "Elite Portfolio",
        price: 19999,
        duration: "Full Day",
        photos: "100 Edited Photos",
        description: "The ultimate portfolio experience for top-tier professionals.",
        images: [
          "/Portfolio/10.jpg",
          "/Portfolio/11.jpg",
          "/Portfolio/2.jpg",
          "/Portfolio/3.jpg",
        ],
        includes: ["Multiple locations", "Unlimited outfit changes", "Full glam team", "Video highlights", "Premium printed album", "Digital rights"],
      },
    ],
  },
  makeup: {
    title: "Makeup Shoot",
    icon: "💄",
    tagline: "Capture Every Flawless Detail",
    banner: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1400&q=80",
    packages: [
      {
        id: "makeup-glam",
        name: "Glam Session",
        price: 3999,
        duration: "1.5 Hours",
        photos: "15 Edited Photos",
        description: "Showcase your makeup artistry with stunning close-up shots.",
        images: [
          "/Makeup/1.jpg",
          "/Makeup/2.jpg",
          "/Makeup/3.jpg",
          "/Makeup/4.jpg",
        ],
        includes: ["Macro lens shots", "Beauty lighting", "Before & after shots", "Digital delivery"],
      },
      {
        id: "makeup-artist",
        name: "MUA Portfolio",
        price: 7999,
        duration: "3 Hours",
        photos: "35 Edited Photos",
        description: "For makeup artists building their professional portfolio.",
        images: [
          "/Makeup/5.jpg",
          "/Makeup/6.jpg",
          "/Makeup/7.jpg",
          "/Makeup/8.jpg",
        ],
        includes: ["Multiple looks", "Detail & full-face shots", "Social media sized exports", "Commercial usage rights"],
      },
    ],
  },
  baby: {
    title: "Baby Shoot",
    icon: "👶",
    tagline: "Precious Moments, Timeless Memories",
    banner: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=1400&q=80",
    packages: [
      {
        id: "baby-newborn",
        name: "Newborn Session",
        price: 5999,
        duration: "2-3 Hours",
        photos: "25 Edited Photos",
        description: "Capture those magical first days with gentle, safe newborn photography.",
        images: [
          "/baby/1.jpg",
          "/baby/2.jpg",
          "/baby/3.jpg",
          "/baby/4.jpg",
        ],
        includes: ["Newborn-safe posing", "Props & wraps included", "Parent shots", "Printed 8x10 photo"],
      },
      {
        id: "baby-milestone",
        name: "Milestone Package",
        price: 8999,
        duration: "3 Hours",
        photos: "40 Edited Photos",
        description: "Document every milestone — 3 months, 6 months, 1st birthday!",
        images: [
          "/baby/5.jpg",
          "/baby/6.jpg",
          "/baby/7.jpg",
          "/baby/8.jpg",
        ],
        includes: ["3 session package", "Cake smash session", "Family portraits", "Photo album", "Canvas print"],
      },
    ],
  },
  product: {
    title: "Product Shoot",
    icon: "📦",
    tagline: "Make Your Products Sell Themselves",
    banner: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1400&q=80",
    packages: [
      {
        id: "product-basic",
        name: "Product Starter",
        price: 2999,
        duration: "2 Hours",
        photos: "10 Products (3 angles each)",
        description: "Clean white background product shots for marketplaces.",
        images: [
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
          "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
          "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80",
          "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
        ],
        includes: ["White background shots", "Shadow removal", "Amazon/Flipkart ready", "High resolution files"],
      },
      {
        id: "product-lifestyle",
        name: "Lifestyle Product",
        price: 7999,
        duration: "4 Hours",
        photos: "30 Lifestyle Photos",
        description: "Contextual shots that show your product in real life scenarios.",
        images: [
          "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
          "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
          "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80",
        ],
        includes: ["Props & styling", "Model if required", "Social media crops", "Website banners"],
      },
    ],
  },
  ecommerce: {
    title: "Ecommerce Shoot",
    icon: "🛒",
    tagline: "Boost Your Online Sales",
    banner: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1400&q=80",
    packages: [
      {
        id: "ecommerce-catalog",
        name: "Catalog Shoot",
        price: 4999,
        duration: "Full Day",
        photos: "50 Products",
        description: "Bulk product photography for your entire ecommerce catalog.",
        images: [
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
          "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&q=80",
          "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
          "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80",
        ],
        includes: ["Ghost mannequin", "Flat lay shots", "Clipping path", "Quick turnaround 48hrs"],
      },
      {
        id: "ecommerce-premium",
        name: "Premium Store Pack",
        price: 14999,
        duration: "2 Days",
        photos: "150 Photos + Videos",
        description: "Complete visual content for launching or revamping your online store.",
        images: [
          "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80",
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
          "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&q=80",
          "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
        ],
        includes: ["Model shoots", "Short reels", "Banner designs", "Social media kit", "Priority delivery"],
      },
    ],
  },
  outdoor: {
    title: "Outdoor Shoot",
    icon: "🌿",
    tagline: "Nature as Your Studio",
    banner: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=80",
    packages: [
      {
        id: "outdoor-golden",
        name: "Golden Hour Session",
        price: 3999,
        duration: "1.5 Hours",
        photos: "20 Edited Photos",
        description: "Magical sunset / sunrise outdoor portraits in natural light.",
        images: [
          "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80",
          "https://images.unsplash.com/photo-1502781252888-9143ba7f074e?w=800&q=80",
          "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
        ],
        includes: ["Location scouting", "Natural light mastery", "Candid + posed shots", "Online gallery"],
      },
      {
        id: "outdoor-adventure",
        name: "Adventure Pack",
        price: 11999,
        duration: "Full Day",
        photos: "60 Edited Photos",
        description: "Travel & adventure photography at scenic locations across the city or beyond.",
        images: [
          "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
          "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80",
          "https://images.unsplash.com/photo-1502781252888-9143ba7f074e?w=800&q=80",
        ],
        includes: ["2 locations", "Drone shots", "Reels content", "Travel allowance included", "Rush delivery option"],
      },
    ],
  },
};
